name: household_ledger
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.3.0
  googleapis: ^16.0.0
  googleapis_auth: ^2.0.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  provider: ^6.1.5+1
  intl: ^0.20.3
  url_launcher: ^6.3.2
  fl_chart: ^0.68.0
  http: ^1.6.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  mocktail: ^1.0.4
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/client_secret.json
     - assets/card_bin_data.json
     - assets/ledger_ingestion_info.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
